<template>
  <q-page class="q-pa-md">
    <q-btn label="Importar Produtos de Exemplo" color="primary" @click="importarProdutos" />
  </q-page>
</template>

<script setup>
import { collection, addDoc } from 'firebase/firestore'
import { db } from 'src/boot/firebase'

const produtosExemplo = [
  {
    nome: 'Shampoo Avon',
    categoria: 'Higiene',
    marca: 'Avon',
    unidade: 'frasco',
    quantidade: 10,
    precoCompra: 10.0,
    precoVenda: 15.99,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Avon',
    codigoInterno: 'AV-HI-001',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2025-08-01',
    ativo: true,
  },
  {
    nome: 'Colônia Jaffa',
    categoria: 'Perfume',
    marca: 'Jaffa',
    unidade: 'frasco',
    quantidade: 5,
    precoCompra: 20.0,
    precoVenda: 29.9,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Jaffa',
    codigoInterno: 'JA-PE-002',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2026-02-15',
    ativo: true,
  },
  {
    nome: 'Batom Vermelho',
    categoria: 'Maquiagem',
    marca: 'Boticário',
    unidade: 'un',
    quantidade: 8,
    precoCompra: 10.5,
    precoVenda: 19.9,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Boticário',
    codigoInterno: 'BO-MA-003',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2025-12-10',
    ativo: true,
  },
  {
    nome: 'Sabonete Hidratante',
    categoria: 'Higiene',
    marca: 'Natura',
    unidade: 'un',
    quantidade: 15,
    precoCompra: 4.0,
    precoVenda: 7.5,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Natura',
    codigoInterno: 'NA-HI-004',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2025-10-30',
    ativo: true,
  },
  {
    nome: 'Base Líquida',
    categoria: 'Maquiagem',
    marca: 'Avon',
    unidade: 'frasco',
    quantidade: 6,
    precoCompra: 15.0,
    precoVenda: 28.0,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Avon',
    codigoInterno: 'AV-MA-005',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2025-11-20',
    ativo: true,
  },
  {
    nome: 'Desodorante Spray',
    categoria: 'Higiene',
    marca: 'Natura',
    unidade: 'frasco',
    quantidade: 12,
    precoCompra: 9.0,
    precoVenda: 17.99,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Natura',
    codigoInterno: 'NA-HI-006',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2026-01-05',
    ativo: true,
  },
  {
    nome: 'Creme para Mãos',
    categoria: 'Higiene',
    marca: 'Boticário',
    unidade: 'tubo',
    quantidade: 7,
    precoCompra: 6.5,
    precoVenda: 12.0,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Boticário',
    codigoInterno: 'BO-HI-007',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2025-09-15',
    ativo: true,
  },
  {
    nome: 'Pó Compacto',
    categoria: 'Maquiagem',
    marca: 'Avon',
    unidade: 'un',
    quantidade: 10,
    precoCompra: 11.0,
    precoVenda: 18.5,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Avon',
    codigoInterno: 'AV-MA-008',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2025-12-25',
    ativo: true,
  },
  {
    nome: 'Condicionador Jaffa',
    categoria: 'Higiene',
    marca: 'Jaffa',
    unidade: 'frasco',
    quantidade: 4,
    precoCompra: 14.0,
    precoVenda: 23.0,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Jaffa',
    codigoInterno: 'JA-HI-009',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2025-08-20',
    ativo: true,
  },
  {
    nome: 'Perfume Essência Rosa',
    categoria: 'Perfume',
    marca: 'Boticário',
    unidade: 'frasco',
    quantidade: 3,
    precoCompra: 32.0,
    precoVenda: 55.0,
    imagemUrl: 'https://via.placeholder.com/150',
    observacoes: '',
    fornecedor: 'Boticário',
    codigoInterno: 'BO-PE-010',
    alertaEstoqueBaixo: 5,
    disponivelParaVenda: true,
    dataCadastro: '2025-05-12',
    dataVencimento: '2026-03-01',
    ativo: true,
  },
]

async function importarProdutos() {
  const ref = collection(db, 'produtos')

  for (const produto of produtosExemplo) {
    await addDoc(ref, produto)
  }

  alert('✅ Produtos importados com sucesso!')
}
</script>
